// Purpose: Defines for all the built-in arguments
// Created on: 4/24/24 @ 7:48 PM

// Copyright (c) 2024, PortalPlayer <email@portalplayer.xyz>
// Licensed under MIT <https://opensource.org/licenses/MIT>

#pragma once

#define SBR_BUILTINARGUMENTS_CURL_VERBOSE "--curl-verbose"
#define SBR_BUILTINARGUMENTS_CURL_VERBOSE_SHORT "-cv"
#define SBR_BUILTINARGUMENTS_HELP "--help"
#define SBR_BUILTINARGUMENTS_HELP_SHORT "-h"
#define SBR_BUILTINARGUMENTS_DISCORD_API "--discord-api"
#define SBR_BUILTINARGUMENTS_DISCORD_API_SHORT "-da"
#define SBR_BUILTINARGUMENTS_DISCORD_API_ROOT "--discord-api-root"
#define SBR_BUILTINARGUMENTS_DISCORD_API_ROOT_SHORT "-dar"
#define SBR_BUILTINARGUMENTS_DISCORD_WEBSOCKET "--discord-websocket"
#define SBR_BUILTINARGUMENTS_DISCORD_WEBSOCKET_SHORT "-dw"
#define SBR_BUILTINARGUMENTS_DISCORD_CDN "--discord-cdn"
#define SBR_BUILTINARGUMENTS_DISCORD_CDN_SHORT "-dc"
#define SBR_BUILTINARGUMENTS_EVENT_BUFFER "--event-buffer"
#define SBR_BUILTINARGUMENTS_EVENT_BUFFER_SHORT "-eb"
#define SBR_BUILTINARGUMENTS_DISABLE_TERMINAL_COMMANDS "--disable-terminal-commands"
#define SBR_BUILTINARGUMENTS_DISABLE_TERMINAL_COMMANDS_SHORT "-dtc"
#define SBR_BUILTINARGUMENTS_DISABLE_SLASH_COMMANDS "--disable-slash-commands"
#define SBR_BUILTINARGUMENTS_DISABLE_SLASH_COMMANDS_SHORT "-dsc"
#define SBR_BUILTINARGUMENTS_DISABLE_CLASSIC_COMMANDS "--disable-classic-commands"
#define SBR_BUILTINARGUMENTS_DISABLE_CLASSIC_COMMANDS_SHORT "-dcc"
#define SBR_BUILTINARGUMENTS_INSECURE "--insecure"
#define SBR_BUILTINARGUMENTS_INSECURE_SHORT "-k"
