// Purpose: Discord permissions
// Created on: 4/24/24 @ 8:07 PM

// Copyright (c) 2024, PortalPlayer <email@portalplayer.xyz>
// Licensed under MIT <https://opensource.org/licenses/MIT>

#pragma once

#include <BaconAPI/Internal/Boolean.h>

#define SBR_DISCORDPERMISSION_CREATE_INSTANT_INVITE 1UL << 0
#define SBR_DISCORDPERMISSION_KICK_MEMBERS 1UL << 1
#define SBR_DISCORDPERMISSION_BAN_MEMBERS 1UL << 2

/**
 * Almost all permissions, and bypasses channel permission overrides. Very dangerous
 */
#define SBR_DISCORDPERMISSION_ADMINISTRATOR 1UL << 3
#define SBR_DISCORDPERMISSION_MANAGE_CHANNELS 1UL << 4
#define SBR_DISCORDPERMISSION_MANAGE_GUILD 1UL << 5
#define SBR_DISCORDPERMISSION_ADD_REACTIONS 1UL << 6
#define SBR_DISCORDPERMISSION_VIEW_AUDIT_LOG 1UL << 7
#define SBR_DISCORDPERMISSION_PRIORITY_SPEAKER 1UL << 8
#define SBR_DISCORDPERMISSION_STREAM 1UL << 9
#define SBR_DISCORDPERMISSION_VIEW_CHANNEL 1UL << 10
#define SBR_DISCORDPERMISSION_SEND_MESSAGES 1UL << 11
#define SBR_DISCORDPERMISSION_SEND_TTS_MESSAGES 1UL << 12
#define SBR_DISCORDPERMISSION_MANAGE_MESSAGES 1UL << 13

/**
 * Misleading name, includes all embeds in general
 */
#define SBR_DISCORDPERMISSION_EMBED_LINKS 1UL << 14
#define SBR_DISCORDPERMISSION_ATTACH_FILES 1UL << 15
#define SBR_DISCORDPERMISSION_READ_MESSAGE_HISTORY 1UL << 16

/**
 * Allow to mention @everyone and @here
 */
#define SBR_DISCORDPERMISSION_MENTION_EVERYONE 1UL << 17
#define SBR_DISCORDPERMISSION_USE_EXTERNAL_EMOJIS 1UL << 18
#define SBR_DISCORDPERMISSION_VIEW_GUILD_INSIGHTS 1UL << 19
#define SBR_DISCORDPERMISSION_CONNECT 1UL << 20
#define SBR_DISCORDPERMISSION_SPEAK 1UL << 21
#define SBR_DISCORDPERMISSION_MUTE_MEMBERS 1UL << 22
#define SBR_DISCORDPERMISSION_DEAFEN_MEMBERS 1UL << 23
#define SBR_DISCORDPERMISSION_MOVE_MEMBERS 1UL << 24
#define SBR_DISCORDPERMISSION_USE_VAD 1UL << 25
#define SBR_DISCORDPERMISSION_CHANGE_NICKNAME 1UL << 26
#define SBR_DISCORDPERMISSION_MANAGE_NICKNAMES 1UL << 27
#define SBR_DISCORDPERMISSION_MANAGE_ROLES 1UL << 28
#define SBR_DISCORDPERMISSION_MANAGE_WEBHOOKS 1UL << 29
#define SBR_DISCORDPERMISSION_MANAGE_GUILD_EXPRESSIONS 1UL << 30
#define SBR_DISCORDPERMISSION_USE_APPLICATION_COMMANDS 1UL << 31
#define SBR_DISCORDPERMISSION_REQUEST_TO_SPEAK 1UL << 32
#define SBR_DISCORDPERMISSION_MANAGE_EVENTS 1UL << 33
#define SBR_DISCORDPERMISSION_MANAGE_THREADS 1UL << 34
#define SBR_DISCORDPERMISSION_CREATE_PUBLIC_THREADS 1UL << 35
#define SBR_DISCORDPERMISSION_CREATE_PRIVATE_THREADS 1UL << 36
#define SBR_DISCORDPERMISSION_USE_EXTERNAL_STICKERS 1UL << 37
#define SBR_DISCORDPERMISSION_SEND_MESSAGES_IN_THREADS 1UL << 38
#define SBR_DISCORDPERMISSION_USE_EMBEDDED_ACTIVITIES 1UL << 39
#define SBR_DISCORDPERMISSION_MODERATE_MEMBERS 1UL << 40
#define SBR_DISCORDPERMISSION_VIEW_CREATOR_MONETIZATION_ANALYTICS 1UL << 41
#define SBR_DISCORDPERMISSION_USE_SOUNDBOARD 1UL << 42
#define SBR_DISCORDPERMISSION_CREATE_GUILD_EXPRESSIONS 1UL << 43
#define SBR_DISCORDPERMISSION_CREATE_EVENTS 1UL << 44
#define SBR_DISCORDPERMISSION_USE_EXTERNAL_SOUNDS 1UL << 45
#define SBR_DISCORDPERMISSION_SEND_VOICE_MESSAGES 1UL << 46
#define SBR_DISCORDPERMISSION_SEND_POLLS 1UL << 49

#define SBR_DISCORDPERMISSION_ALL SBR_DISCORDPERMISSION_CREATE_INSTANT_INVITE | SBR_DISCORDPERMISSION_KICK_MEMBERS | \
                                  SBR_DISCORDPERMISSION_BAN_MEMBERS | SBR_DISCORDPERMISSION_ADMINISTRATOR | \
                                  SBR_DISCORDPERMISSION_MANAGE_CHANNELS | SBR_DISCORDPERMISSION_MANAGE_GUILD | \
                                  SBR_DISCORDPERMISSION_ADD_REACTIONS | SBR_DISCORDPERMISSION_VIEW_AUDIT_LOG | \
                                  SBR_DISCORDPERMISSION_PRIORITY_SPEAKER | SBR_DISCORDPERMISSION_STREAM | \
                                  SBR_DISCORDPERMISSION_VIEW_CHANNEL | SBR_DISCORDPERMISSION_SEND_MESSAGES | \
                                  SBR_DISCORDPERMISSION_SEND_TTS_MESSAGES | SBR_DISCORDPERMISSION_MANAGE_MESSAGES | \
                                  SBR_DISCORDPERMISSION_EMBED_LINKS | SBR_DISCORDPERMISSION_ATTACH_FILES | \
                                  SBR_DISCORDPERMISSION_READ_MESSAGE_HISTORY | SBR_DISCORDPERMISSION_MENTION_EVERYONE | \
                                  SBR_DISCORDPERMISSION_USE_EXTERNAL_EMOJIS | SBR_DISCORDPERMISSION_VIEW_GUILD_INSIGHTS | \
                                  SBR_DISCORDPERMISSION_CONNECT | SBR_DISCORDPERMISSION_SPEAK | \
                                  SBR_DISCORDPERMISSION_MUTE_MEMBERS | SBR_DISCORDPERMISSION_DEAFEN_MEMBERS | \
                                  SBR_DISCORDPERMISSION_MOVE_MEMBERS | SBR_DISCORDPERMISSION_USE_VAD | \
                                  SBR_DISCORDPERMISSION_CHANGE_NICKNAME | SBR_DISCORDPERMISSION_MANAGE_NICKNAMES | \
                                  SBR_DISCORDPERMISSION_MANAGE_ROLES | SBR_DISCORDPERMISSION_MANAGE_WEBHOOKS | \
                                  SBR_DISCORDPERMISSION_MANAGE_GUILD_EXPRESSIONS | SBR_DISCORDPERMISSION_USE_APPLICATION_COMMANDS | \
                                  SBR_DISCORDPERMISSION_REQUEST_TO_SPEAK | SBR_DISCORDPERMISSION_MANAGE_EVENTS | \
                                  SBR_DISCORDPERMISSION_MANAGE_THREADS | SBR_DISCORDPERMISSION_CREATE_PUBLIC_THREADS | \
                                  SBR_DISCORDPERMISSION_CREATE_PRIVATE_THREADS | SBR_DISCORDPERMISSION_USE_EXTERNAL_STICKERS | \
                                  SBR_DISCORDPERMISSION_SEND_MESSAGES_IN_THREADS | SBR_DISCORDPERMISSION_USE_EMBEDDED_ACTIVITIES | \
                                  SBR_DISCORDPERMISSION_MODERATE_MEMBERS | SBR_DISCORDPERMISSION_VIEW_CREATOR_MONETIZATION_ANALYTICS | \
                                  SBR_DISCORDPERMISSION_USE_SOUNDBOARD | SBR_DISCORDPERMISSION_CREATE_GUILD_EXPRESSIONS | \
                                  SBR_DISCORDPERMISSION_CREATE_EVENTS | SBR_DISCORDPERMISSION_USE_EXTERNAL_SOUNDS | \
                                  SBR_DISCORDPERMISSION_SEND_VOICE_MESSAGES | SBR_DISCORDPERMISSION_SEND_POLLS
#define SBR_DISCORDPERMISSION_DEFAULT SBR_DISCORDPERMISSION_VIEW_CHANNEL | SBR_DISCORDPERMISSION_CREATE_GUILD_EXPRESSIONS | \
                                      SBR_DISCORDPERMISSION_CREATE_INSTANT_INVITE | SBR_DISCORDPERMISSION_CHANGE_NICKNAME | \
                                      SBR_DISCORDPERMISSION_SEND_MESSAGES | SBR_DISCORDPERMISSION_SEND_MESSAGES_IN_THREADS | \
                                      SBR_DISCORDPERMISSION_CREATE_PUBLIC_THREADS | SBR_DISCORDPERMISSION_CREATE_PRIVATE_THREADS | \
                                      SBR_DISCORDPERMISSION_EMBED_LINKS | SBR_DISCORDPERMISSION_ATTACH_FILES | \
                                      SBR_DISCORDPERMISSION_ADD_REACTIONS | SBR_DISCORDPERMISSION_USE_EXTERNAL_EMOJIS | \
                                      SBR_DISCORDPERMISSION_USE_EXTERNAL_STICKERS | SBR_DISCORDPERMISSION_MENTION_EVERYONE | \
                                      SBR_DISCORDPERMISSION_READ_MESSAGE_HISTORY | SBR_DISCORDPERMISSION_USE_APPLICATION_COMMANDS | \
                                      SBR_DISCORDPERMISSION_SEND_VOICE_MESSAGES | SBR_DISCORDPERMISSION_SEND_POLLS | \
                                      SBR_DISCORDPERMISSION_CONNECT | SBR_DISCORDPERMISSION_SPEAK | \
                                      SBR_DISCORDPERMISSION_STREAM | SBR_DISCORDPERMISSION_USE_EMBEDDED_ACTIVITIES | \
                                      SBR_DISCORDPERMISSION_USE_SOUNDBOARD | SBR_DISCORDPERMISSION_USE_VAD | \
                                      SBR_DISCORDPERMISSION_CREATE_EVENTS

#define SBR_DISCORDPERMISSION_SEND_TEXT_TO_SPEECH_MESSAGES SBR_DISCORDPERMISSION_SEND_TTS_MESSAGES
#define SBR_DISCORDPERMISSION_EMBEDS SBR_DISCORDPERMISSION_EMBED_LINKS
#define SBR_DISCORDPERMISSION_USE_VOICE_ACTIVITY_DETECTION SBR_DISCORDPERMISSION_USE_VAD
 
#define SBR_DISCORDPERMISSION_CREATE_EXPRESSIONS SBR_DISCORDPERMISSION_CREATE_GUILD_EXPRESSIONS
#define SBR_DISCORDPERMISSION_MANAGE_EXPRESSIONS SBR_DISCORDPERMISSION_MANAGE_GUILD_EXPRESSIONS
#define SBR_DISCORDPERMISSION_MANAGE_SERVER SBR_DISCORDPERMISSION_MANAGE_GUILD
#define SBR_DISCORDPERMISSION_CREATE_INVITE SBR_DISCORDPERMISSION_CREATE_INSTANT_INVITE
#define SBR_DISCORDPERMISSION_TIMEOUT_MEMBERS SBR_DISCORDPERMISSION_MODERATE_MEMBERS
#define SBR_DISCORDPERMISSION_CREATE_POLLS SBR_DISCORDPERMISSION_SEND_POLLS
#define SBR_DISCORDPERMISSION_VIDEO SBR_DISCORDPERMISSION_STREAM
#define SBR_DISCORDPERMISSION_USE_ACTIVITIES SBR_DISCORDPERMISSION_USE_EMBEDDED_ACTIVITIES

BA_Boolean SBR_DiscordPermissions_Requires2FA(unsigned long permission);
BA_Boolean SBR_DiscordPermissions_IsTextChannelPermission(unsigned long permission);
BA_Boolean SBR_DiscordPermissions_IsVoicePermission(unsigned long permission);
BA_Boolean SBR_DiscordPermissions_IsStagePermission(unsigned long permission);
