// Purpose: Discord permissions
// Created on: 4/24/24 @ 8:07 PM

// Copyright (c) 2024, PortalPlayer <email@portalplayer.xyz>
// Licensed under MIT <https://opensource.org/licenses/MIT>

#pragma once

#include <BaconAPI/Internal/Boolean.h>

typedef enum {
    SBR_DISCORDPERMISSION_CREATE_INSTANT_INVITE = 1,
    SBR_DISCORDPERMISSION_KICK_MEMBERS,
    SBR_DISCORDPERMISSION_BAN_MEMBERS = 1 << 2,

    /**
     * Almost all permissions, and bypasses channel permission overrides. Very dangerous
     */
    SBR_DISCORDPERMISSION_ADMINISTRATOR = 1 << 3,
    SBR_DISCORDPERMISSION_MANAGE_CHANNELS = 1 << 4,
    SBR_DISCORDPERMISSION_MANAGE_GUILD = 1 << 5,
    SBR_DISCORDPERMISSION_ADD_REACTIONS = 1 << 6,
    SBR_DISCORDPERMISSION_VIEW_AUDIT_LOG = 1 << 7,
    SBR_DISCORDPERMISSION_PRIORITY_SPEAKER = 1 << 8,
    SBR_DISCORDPERMISSION_STREAM = 1 << 9,
    SBR_DISCORDPERMISSION_VIEW_CHANNEL = 1 << 10,
    SBR_DISCORDPERMISSION_SEND_MESSAGES = 1 << 11,
    SBR_DISCORDPERMISSION_SEND_TTS_MESSAGES = 1 << 12,
    SBR_DISCORDPERMISSION_MANAGE_MESSAGES = 1 << 13,

    /**
     * Misleading name, includes all embeds in general
     */
    SBR_DISCORDPERMISSION_EMBED_LINKS = 1 << 14,
    SBR_DISCORDPERMISSION_ATTACH_FILES = 1 << 15,
    SBR_DISCORDPERMISSION_READ_MESSAGE_HISTORY = 1 << 16,

    /**
     * Allow to mention @everyone and @here
     */
    SBR_DISCORDPERMISSION_MENTION_EVERYONE = 1 << 17,
    SBR_DISCORDPERMISSION_USE_EXTERNAL_EMOJIS = 1 << 18,
    SBR_DISCORDPERMISSION_VIEW_GUILD_INSIGHTS = 1 << 19,
    SBR_DISCORDPERMISSION_CONNECT = 1 << 20,
    SBR_DISCORDPERMISSION_SPEAK = 1 << 21,
    SBR_DISCORDPERMISSION_MUTE_MEMBERS = 1 << 22,
    SBR_DISCORDPERMISSION_DEAFEN_MEMBERS = 1 << 23,
    SBR_DISCORDPERMISSION_MOVE_MEMBERS = 1 << 24,
    SBR_DISCORDPERMISSION_USE_VAD = 1 << 25,
    SBR_DISCORDPERMISSION_CHANGE_NICKNAME = 1 << 26,
    SBR_DISCORDPERMISSION_MANAGE_NICKNAMES = 1 << 27,
    SBR_DISCORDPERMISSION_MANAGE_ROLES = 1 << 28,
    SBR_DISCORDPERMISSION_MANAGE_WEBHOOKS = 1 << 29,
    SBR_DISCORDPERMISSION_MANAGE_GUILD_EXPRESSIONS = 1 << 30,
    SBR_DISCORDPERMISSION_USE_APPLICATION_COMMANDS = 1 << 31,
    SBR_DISCORDPERMISSION_REQUEST_TO_SPEAK = 1 << 32,
    SBR_DISCORDPERMISSION_MANAGE_EVENTS = 1 << 33,
    SBR_DISCORDPERMISSION_MANAGE_THREADS = 1 << 34,
    SBR_DISCORDPERMISSION_CREATE_PUBLIC_THREADS = 1 << 35,
    SBR_DISCORDPERMISSION_CREATE_PRIVATE_THREADS = 1 << 36,
    SBR_DISCORDPERMISSION_USE_EXTERNAL_STICKERS = 1 << 37,
    SBR_DISCORDPERMISSION_SEND_MESSAGES_IN_THREADS = 1 << 38,
    SBR_DISCORDPERMISSION_USE_EMBEDDED_ACTIVITIES = 1 << 39,
    SBR_DISCORDPERMISSION_MODERATE_MEMBERS = 1 << 40,
    SBR_DISCORDPERMISSION_VIEW_CREATOR_MONETIZATION_ANALYTICS = 1 << 41,
    SBR_DISCORDPERMISSION_USE_SOUNDBOARD = 1 << 42,
    SBR_DISCORDPERMISSION_CREATE_GUILD_EXPRESSIONS = 1 << 43,
    SBR_DISCORDPERMISSION_CREATE_EVENTS = 1 << 44,
    SBR_DISCORDPERMISSION_USE_EXTERNAL_SOUNDS = 1 << 45,
    SBR_DISCORDPERMISSION_SEND_VOICE_MESSAGES = 1 << 46,
    SBR_DISCORDPERMISSION_SEND_POLLS = 1 << 49,

    SBR_DISCORDPERMISSION_ALL = SBR_DISCORDPERMISSION_CREATE_INSTANT_INVITE | SBR_DISCORDPERMISSION_KICK_MEMBERS |
                                SBR_DISCORDPERMISSION_BAN_MEMBERS | SBR_DISCORDPERMISSION_ADMINISTRATOR |
                                SBR_DISCORDPERMISSION_MANAGE_CHANNELS | SBR_DISCORDPERMISSION_MANAGE_GUILD |
                                SBR_DISCORDPERMISSION_ADD_REACTIONS | SBR_DISCORDPERMISSION_VIEW_AUDIT_LOG |
                                SBR_DISCORDPERMISSION_PRIORITY_SPEAKER | SBR_DISCORDPERMISSION_STREAM |
                                SBR_DISCORDPERMISSION_VIEW_CHANNEL | SBR_DISCORDPERMISSION_SEND_MESSAGES |
                                SBR_DISCORDPERMISSION_SEND_TTS_MESSAGES | SBR_DISCORDPERMISSION_MANAGE_MESSAGES |
                                SBR_DISCORDPERMISSION_EMBED_LINKS | SBR_DISCORDPERMISSION_ATTACH_FILES |
                                SBR_DISCORDPERMISSION_READ_MESSAGE_HISTORY | SBR_DISCORDPERMISSION_MENTION_EVERYONE |
                                SBR_DISCORDPERMISSION_USE_EXTERNAL_EMOJIS | SBR_DISCORDPERMISSION_VIEW_GUILD_INSIGHTS |
                                SBR_DISCORDPERMISSION_CONNECT | SBR_DISCORDPERMISSION_SPEAK |
                                SBR_DISCORDPERMISSION_MUTE_MEMBERS | SBR_DISCORDPERMISSION_DEAFEN_MEMBERS |
                                SBR_DISCORDPERMISSION_MOVE_MEMBERS | SBR_DISCORDPERMISSION_USE_VAD |
                                SBR_DISCORDPERMISSION_CHANGE_NICKNAME | SBR_DISCORDPERMISSION_MANAGE_NICKNAMES |
                                SBR_DISCORDPERMISSION_MANAGE_ROLES | SBR_DISCORDPERMISSION_MANAGE_WEBHOOKS |
                                SBR_DISCORDPERMISSION_MANAGE_GUILD_EXPRESSIONS | SBR_DISCORDPERMISSION_USE_APPLICATION_COMMANDS |
                                SBR_DISCORDPERMISSION_REQUEST_TO_SPEAK | SBR_DISCORDPERMISSION_MANAGE_EVENTS |
                                SBR_DISCORDPERMISSION_MANAGE_THREADS | SBR_DISCORDPERMISSION_CREATE_PUBLIC_THREADS |
                                SBR_DISCORDPERMISSION_CREATE_PRIVATE_THREADS | SBR_DISCORDPERMISSION_USE_EXTERNAL_STICKERS |
                                SBR_DISCORDPERMISSION_SEND_MESSAGES_IN_THREADS | SBR_DISCORDPERMISSION_USE_EMBEDDED_ACTIVITIES |
                                SBR_DISCORDPERMISSION_MODERATE_MEMBERS | SBR_DISCORDPERMISSION_VIEW_CREATOR_MONETIZATION_ANALYTICS |
                                SBR_DISCORDPERMISSION_USE_SOUNDBOARD | SBR_DISCORDPERMISSION_CREATE_GUILD_EXPRESSIONS |
                                SBR_DISCORDPERMISSION_CREATE_EVENTS | SBR_DISCORDPERMISSION_USE_EXTERNAL_SOUNDS |
                                SBR_DISCORDPERMISSION_SEND_VOICE_MESSAGES | SBR_DISCORDPERMISSION_SEND_POLLS,
    SBR_DISCORDPERMISSION_DEFAULT = SBR_DISCORDPERMISSION_VIEW_CHANNEL | SBR_DISCORDPERMISSION_CREATE_GUILD_EXPRESSIONS |
                                    SBR_DISCORDPERMISSION_CREATE_INSTANT_INVITE | SBR_DISCORDPERMISSION_CHANGE_NICKNAME |
                                    SBR_DISCORDPERMISSION_SEND_MESSAGES | SBR_DISCORDPERMISSION_SEND_MESSAGES_IN_THREADS |
                                    SBR_DISCORDPERMISSION_CREATE_PUBLIC_THREADS | SBR_DISCORDPERMISSION_CREATE_PRIVATE_THREADS |
                                    SBR_DISCORDPERMISSION_EMBED_LINKS | SBR_DISCORDPERMISSION_ATTACH_FILES |
                                    SBR_DISCORDPERMISSION_ADD_REACTIONS | SBR_DISCORDPERMISSION_USE_EXTERNAL_EMOJIS |
                                    SBR_DISCORDPERMISSION_USE_EXTERNAL_STICKERS | SBR_DISCORDPERMISSION_MENTION_EVERYONE |
                                    SBR_DISCORDPERMISSION_READ_MESSAGE_HISTORY | SBR_DISCORDPERMISSION_USE_APPLICATION_COMMANDS |
                                    SBR_DISCORDPERMISSION_SEND_VOICE_MESSAGES | SBR_DISCORDPERMISSION_SEND_POLLS |
                                    SBR_DISCORDPERMISSION_CONNECT | SBR_DISCORDPERMISSION_SPEAK |
                                    SBR_DISCORDPERMISSION_STREAM | SBR_DISCORDPERMISSION_USE_EMBEDDED_ACTIVITIES |
                                    SBR_DISCORDPERMISSION_USE_SOUNDBOARD | SBR_DISCORDPERMISSION_USE_VAD |
                                    SBR_DISCORDPERMISSION_CREATE_EVENTS,

    SBR_DISCORDPERMISSION_SEND_TEXT_TO_SPEECH_MESSAGES = SBR_DISCORDPERMISSION_SEND_TTS_MESSAGES,
    SBR_DISCORDPERMISSION_EMBEDS = SBR_DISCORDPERMISSION_EMBED_LINKS,
    SBR_DISCORDPERMISSION_USE_VOICE_ACTIVITY_DETECTION = SBR_DISCORDPERMISSION_USE_VAD,
 
    SBR_DISCORDPERMISSION_CREATE_EXPRESSIONS = SBR_DISCORDPERMISSION_CREATE_GUILD_EXPRESSIONS,
    SBR_DISCORDPERMISSION_MANAGE_EXPRESSIONS = SBR_DISCORDPERMISSION_MANAGE_GUILD_EXPRESSIONS,
    SBR_DISCORDPERMISSION_MANAGE_SERVER = SBR_DISCORDPERMISSION_MANAGE_GUILD,
    SBR_DISCORDPERMISSION_CREATE_INVITE = SBR_DISCORDPERMISSION_CREATE_INSTANT_INVITE,
    SBR_DISCORDPERMISSION_TIMEOUT_MEMBERS = SBR_DISCORDPERMISSION_MODERATE_MEMBERS,
    SBR_DISCORDPERMISSION_CREATE_POLLS = SBR_DISCORDPERMISSION_SEND_POLLS,
    SBR_DISCORDPERMISSION_VIDEO = SBR_DISCORDPERMISSION_STREAM,
    SBR_DISCORDPERMISSION_USE_ACTIVITIES = SBR_DISCORDPERMISSION_USE_EMBEDDED_ACTIVITIES
} SBR_DiscordPermissions;

BA_Boolean SBR_DiscordPermissions_Requires2FA(SBR_DiscordPermissions permission);
BA_Boolean SBR_DiscordPermissions_IsTextChannelPermission(SBR_DiscordPermissions permission);
BA_Boolean SBR_DiscordPermissions_IsVoicePermission(SBR_DiscordPermissions permission);
BA_Boolean SBR_DiscordPermissions_IsStagePermission(SBR_DiscordPermissions permission);
